name: orgsync
description: "Sistema SaaS de gerenciamento organizacional"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  provider: ^6.1.1
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^5.0.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  mockito: ^5.4.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  injectable_generator: ^2.5.0
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

 